version: '3.8'

services:
  msr-lean:
    image: azdevopsdhl5acr.azurecr.io/msr-1011-lean-original-recipe:Fixes_22-09-20
    ports:
      - 5555:5555
    volumes:
      - ${MY_MSR_LICENSE_FILE}:/tmp/license.xml
    environment:
      - SAG_IS_LICENSE_FILE=/tmp/license.xml