version: '3.8'

services:
  msr-lean:
    image: ${CONTAINER_REGISTRY_URL}/${CONTAINER_IMAGE_REPOSITORY}:${CONTAINER_IMAGE_TAG}
    ports:
      - ${HOST_PORT_PREFIX}55:5555
    volumes:
      - ${HOST_MSR_LICENSE_FILE}:/tmp/license.xml
      - ./application.properties:/tmp/application.properties
      - ../../:/mnt/project-home/
      - ./local/:/mnt/local/
      - ./scripts/:/mnt/scripts/
      #our code
      - ../../code/is-packages/MyNewsService/:${GUEST_IS_HOME}/packages/MyNewsService/
      - ../../code/is-packages/MyMailService/:${GUEST_IS_HOME}/packages/MyMailService/
    environment:
      - SAG_IS_LICENSE_FILE=/tmp/license.xml
      - SAG_IS_CONFIG_PROPERTIES=/tmp/application.properties
    #entrypoint: /mnt/scripts/entrypoint.sh